version: "3.9"
services:

  web:
    build: .
    volumes:
      - .:/project
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:5.0.7
    command: redis-server
    ports:
      - '6379:6379'

  sidekiq:
      depends_on:
        - redis
      build: .
      command: bundle exec sidekiq
      volumes:
        - .:/project
      env_file:
        - .env
      entrypoint: ./sidekiq-entrypoint.sh